name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Build
      run: cargo build --release --verbose
    - name: Test
      run: cargo test --verbose
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: pngme
        path: ./target/release/pngme
